# Load libraries

library(tibble)
library(dplyr)
library(ggplot2)
library(rjson)
library(rms)
library(scales)


# Load data

covid <- data.frame(readxl::read_xlsx("Zejscie_data_Adam.xlsx"))

# Demographical data source: http://demografia.stat.gov.pl/bazademografia/

gus_life <- data.frame(readxl::read_xlsx("gus_life_expectancy.xlsx"))
gus_population <- data.frame(readxl::read_xlsx("gus_population.xlsx"))

colnames(gus_population) <- c("age","male_pop","female_pop")

if(nrow(filter(covid, Wiek>100))>0){
  covid[covid$Wiek>100,]$Wiek <- 100
}

# Scraped live covid infected and deceased data from API
# API data source: https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

live_data_source <- fromJSON(file="https://api.apify.com/v2/key-value-stores/3Po6TV7wTht4vIEid/records/LATEST?disableRedirect=true")
live_infected <- live_data_source$infected
live_deceased <- live_data_source$deceased

# Multiplier to adjust known cases for live numbers

known_deceased <- (covid %>% filter(Zejście.choroby=="Zgon z powodu zgłoszonej choroby") %>% count())$n
multiplier <- live_deceased/known_deceased

# Covid death rate calculation for only infected and all residents

covid_male <- covid %>% filter(Płeć == "Mężczyzna")
covid_female <- covid %>% filter(Płeć == "Kobieta")

covid_male_ratio <- data.frame(covid_male %>% 
                              group_by(Wiek, Zejście.choroby) %>% 
                              summarise(N = n()) %>% 
                              group_by(Wiek) %>% 
                              mutate(Total = sum(N), 
                                     Ratio = round(N/Total, 10),
                                     Sex = "Male",
                                     Type = "covid_ill") %>%
                              filter(Zejście.choroby=="Zgon z powodu zgłoszonej choroby"))

covid_female_ratio <- data.frame(covid_female %>% 
                                 group_by(Wiek, Zejście.choroby) %>% 
                                 summarise(N = n()) %>% 
                                 group_by(Wiek) %>% 
                                 mutate(Total = sum(N), 
                                        Ratio = round(N/Total, 10),
                                        Sex = "Female",
                                        Type = "covid_ill") %>%
                                 filter(Zejście.choroby=="Zgon z powodu zgłoszonej choroby"))


covid_ratio_ill <- rbind(covid_male_ratio, covid_female_ratio)
covid_ratio_ill <- select(covid_ratio_ill, c(age=Wiek,death_prob=Ratio,sex=Sex, total_deaths = N, type=Type))

covid_ratio_all <- merge(covid_ratio_ill, gus_population)
covid_ratio_all <- covid_ratio_all %>% mutate(type="covid_all", death_prob=ifelse(sex=="male", total_deaths*multiplier/male_pop, total_deaths*multiplier/female_pop))

covid_ratio <- select(rbind(covid_ratio_ill, select(covid_ratio_all, -c(male_pop, female_pop))), -total_deaths)


# Combined data frame of GUS death rate and covid calculated rates

plot_dat <- select(gus_life, c(age,death_prob,sex))
plot_dat <- cbind(plot_dat, type=rep("gus",nrow(plot_dat)))
plot_dat <- rbind(plot_dat, covid_ratio)

# Ploting the results: logarithmic scale of death rate by age
# Plot 1: Raw data

log_breaks <- function(n = 10){
  function(x) {
    axisTicks(log10(range(x, na.rm = TRUE)), log = TRUE, n = n)
  }
}

plot_dat %>%
  arrange(death_prob) %>%
  mutate(type = factor(type, levels=c("gus", "covid_ill", "covid_all"))) %>%
  ggplot(aes(x=age, y=death_prob)) +
  geom_line(aes(color=sex, linetype=type), lwd=0.8) +
  scale_colour_manual(values = c("violetred3", "royalblue3")) +
  ggtitle("Death Rate", subtitle = "(Logarithmic scale)") +
  scale_x_continuous(breaks=seq(0,100,10)) +
  scale_y_continuous(trans = 'log10', 
                     breaks = log_breaks(),
                     labels = percent) +
  xlab("Age") + ylab("Death probability") +
  labs(color = "Sex") +
  scale_linetype_manual(name = "Death risk type",
                        values = c("solid","longdash","dotted"),
                        labels = c("Normal", "Generated by COVID-19 amongst infected patients", "Generated by COVID-19 amongst all residents")) +
  DALEX::theme_drwhy() +
  theme(legend.position="bottom", legend.direction = "vertical",
        legend.key.width = unit(2.3,"line"), legend.text = element_text(colour = "blue"),
        legend.title = element_text(colour = "blue"))


  
# Logistic Regression model based on known Covid cases

logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}  

covid_mod <- covid %>% select(Zejście.choroby, Wiek, Płeć) %>%
             transmute(Survived = ifelse(Zejście.choroby=="Zgon z powodu zgłoszonej choroby" & !is.na(Zejście.choroby),0,1),
             Age=Wiek,
             Sex=ifelse(Płeć=="Mężczyzna","Male","Female"))
  
Age <- covid_mod$Age
Sex <- covid_mod$Sex
  
ddist <- datadist(Age, Sex)
options(datadist='ddist')
model <- lrm(Survived ~ rcs(Age) + Sex, data = covid_mod)  
results <- Predict(model, Age, Sex)

plot_mod <- results %>% transmute(age = Age, sex = Sex, death_prob = 1-logit2prob(yhat), type = "logreg")
plot_dat2 <- rbind(transmute(gus_life, age, death_prob, sex, type="gus"), plot_mod)

# Ploting the results: logarithmic scale of death rate by age
# Plot 2: Modeled data (logistic regression) for Covid-generated death probability

plot_dat2 %>%
  arrange(death_prob) %>%
  mutate(type = factor(type, levels=c("gus", "logreg"))) %>%
  ggplot(aes(x=age, y=death_prob)) +
  geom_line(aes(color=sex, linetype=type), lwd=0.8) +
  scale_colour_manual(values = c("violetred3", "royalblue3")) +
  ggtitle("Death Rate", subtitle = "Modeled using logistic regression\n(Logarithmic scale)") +
  scale_x_continuous(breaks=seq(0,100,10)) +
  scale_y_continuous(trans = 'log10', 
                     breaks = log_breaks(),
                     labels = percent) +
  xlab("Age") + ylab("Death probability") +
  labs(color = "Sex") +
  scale_linetype_manual(name = "Death risk type",
                        values = c("solid","longdash"),
                        labels = c("Normal", "Generated by COVID-19 amongst infected patients")) +
  DALEX::theme_drwhy() +
  theme(legend.position="bottom", legend.direction = "vertical",
        legend.key.width = unit(2,"line"), legend.text = element_text(colour = "blue"),
        legend.title = element_text(colour = "blue"))



# Creating splines for raw data

gus_dat3 <- select(gus_life, c(age,death_prob,sex)) %>% mutate(type="gus")

plot_dat3 <- covid_ratio %>%
  arrange(death_prob) %>%
  mutate(type = factor(type, levels=c("gus", "covid_ill", "covid_all")))

sp_male_ill<-plot_dat3 %>% filter(type=="covid_ill", sex=="Male")
sp_female_ill<-plot_dat3 %>% filter(type=="covid_ill", sex=="Female")

n <- 1000

sp_male_ill <- data.frame(spline(sp_male_ill, n=n))
colnames(sp_male_ill) <- c("age","death_prob")
sp_female_ill <- data.frame(spline(sp_female_ill, n=n))
colnames(sp_female_ill) <- c("age","death_prob")

sp_male_all<-plot_dat3 %>% filter(type=="covid_all", sex=="Male")
sp_female_all<-plot_dat3 %>% filter(type=="covid_all", sex=="Female")

sp_male_all <- data.frame(spline(sp_male_all, n=n))
colnames(sp_male_all) <- c("age","death_prob")
sp_female_all <- data.frame(spline(sp_female_all, n=n))
colnames(sp_female_all) <- c("age","death_prob")

# Ploting the results: logarithmic scale of death rate by age
# Plot 3: Raw data + splines for Covid-generated death probability

ggplot(data = plot_dat3, aes(x=age, y=death_prob)) +
  geom_point(aes(color=sex, shape=type)) +
  geom_line(data=sp_male_ill, color = "royalblue3", alpha = 0.8) +
  geom_line(data=sp_female_ill, color = "violetred3", alpha = 0.8) +
  geom_line(data=sp_male_all, color = "royalblue3", alpha = 0.8) +
  geom_line(data=sp_female_all, color = "violetred3", alpha = 0.8) +
  geom_line(data=gus_dat3, aes(color=sex, linetype=type)) + 
  scale_colour_manual(values = c("violetred3", "royalblue3")) +
  ggtitle("Death Rate", subtitle = "(Logarithmic scale)") +
  scale_x_continuous(breaks=seq(0,100,10)) +
  scale_y_continuous(trans = 'log10', 
                     breaks = log_breaks(),
                      labels = percent) +
  xlab("Age") + ylab("Death probability") +
  labs(color = "Sex") +
  scale_shape_manual(name = " ",
                        values = c(19,17),
                        labels = c("Generated by COVID-19 amongst infected patients", "Generated by COVID-19 amongst all residents")) +
  scale_linetype_manual(name = " Death risk type",
                        values = c("solid"),
                        labels = c("Normal")) +
  DALEX::theme_drwhy() +
  theme(legend.position="bottom", legend.direction = "vertical",
        legend.text = element_text(colour = "blue"),
        legend.title = element_text(colour = "blue"))

