library(tibble)
library(dplyr)
library(ggplot2)
library(rjson)

# Load data

data_source <- "Zejscie_data_Adam.xlsx"
data_source <- "~/Dropbox/__smiertelnosc_co_id__/dane_2020_07_01/Zejscie_data.xlsx"
covid <- data.frame(readxl::read_xlsx(data_source))

# Demographical data source: http://demografia.stat.gov.pl/bazademografia/

gus_life <- data.frame(readxl::read_xlsx("gus_life_expectancy.xlsx"))
gus_population <- data.frame(readxl::read_xlsx("gus_population.xlsx"))

colnames(gus_population) <- c("age","male_pop","female_pop")

if(nrow(dplyr::filter(covid, Wiek>100))>0){
  covid[covid$Wiek>100,]$Wiek <- 100
}

# Scraped live covid infected and deceased data from API
# API data source: https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2

live_data_source <- fromJSON(file="https://api.apify.com/v2/key-value-stores/3Po6TV7wTht4vIEid/records/LATEST?disableRedirect=true")
live_infected <- live_data_source$infected
live_deceased <- live_data_source$deceased

# Multiplier to adjust known cases for live numbers

known_deceased <- (covid %>% filter(Zejście.choroby=="Zgon z powodu zgłoszonej choroby") %>% count())$n
multiplier <- live_deceased/known_deceased

# Covid death rate calculation for only infected and all residents

covid_male <- covid %>% filter(Płeć == "Mężczyzna")
covid_female <- covid %>% filter(Płeć == "Kobieta")

covid_male_ratio <- data.frame(covid_male %>% 
                              group_by(Wiek, Zejście.choroby) %>% 
                              summarise(N = n()) %>% 
                              group_by(Wiek) %>% 
                              mutate(Total = sum(N), 
                                     Ratio = round(N/Total, 10),
                                     Sex = "Male",
                                     Type = "covid_ill") %>%
                              filter(Zejście.choroby=="Zgon z powodu zgłoszonej choroby"))

covid_female_ratio <- data.frame(covid_female %>% 
                                 group_by(Wiek, Zejście.choroby) %>% 
                                 summarise(N = n()) %>% 
                                 group_by(Wiek) %>% 
                                 mutate(Total = sum(N), 
                                        Ratio = round(N/Total, 10),
                                        Sex = "Female",
                                        Type = "covid_ill") %>%
                                 filter(Zejście.choroby=="Zgon z powodu zgłoszonej choroby"))


covid_ratio_ill <- rbind(covid_male_ratio, covid_female_ratio)
covid_ratio_ill <- select(covid_ratio_ill, c(age=Wiek,death_prob=Ratio,sex=Sex, total_deaths = N, type=Type))

covid_ratio_all <- merge(covid_ratio_ill, gus_population)
covid_ratio_all <- covid_ratio_all %>% mutate(type="covid_all", death_prob=ifelse(sex=="male", total_deaths*multiplier/male_pop, total_deaths*multiplier/female_pop))

covid_ratio <- select(rbind(covid_ratio_ill, select(covid_ratio_all, -c(male_pop, female_pop))), -total_deaths)


# Combined data frame of GUS death rate and covid calculated rates

plot_dat <- select(gus_life, c(age,death_prob,sex))
plot_dat <- cbind(plot_dat, type=rep("gus",nrow(plot_dat)))
plot_dat <- rbind(plot_dat, covid_ratio)

# Ploting the results: logarithmic scale of death rate by age

plot_dat %>%
  arrange(death_prob) %>%
  mutate(type = factor(type, levels=c("gus", "covid_ill", "covid_all"))) %>%
  ggplot(aes(x=age, y=log(death_prob))) +
  geom_line(aes(color=sex, linetype=type), lwd=0.8) +
  scale_colour_manual(values = c("violetred3", "royalblue3")) +
  ggtitle("Death Rate", subtitle = "(Logarithmic scale)") +
  scale_x_continuous(breaks=seq(0,100,10)) +
  xlab("Age") + ylab("Death probability") +
  labs(color = "Sex") +
  scale_linetype_manual(name = "Death risk type",
                        values = c("solid","longdash","dotted"),
                        labels = c("Normal", "Generated by COVID-19 amongst infected patients", "Generated by COVID-19 amongst all residents")) +
  DALEX::theme_drwhy() +
  theme(legend.position="bottom", legend.direction = "vertical",
        legend.key.width = unit(2,"line"), legend.text = element_text(colour = "blue"),
        legend.title = element_text(colour = "blue")) -> plmort

ggsave("death_rate_2020_07_01.png", plmort, width = 10, height = 8)
